name: gradswap
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  firebase_core: ^3.13.1
  go_router: ^13.1.0
  flutter_riverpod: ^2.3.0
  firebase_auth: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  material_color_utilities: ^0.12.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  test_api: ^0.7.6
  vm_service: ^15.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/image_dark.png
    - assets/images/branding.png
    - assets/images/branding_dark.png
    - assets/images/background.png
    
    # onboarding
    - assets/images/onboarding/onboard1.png
    - assets/images/onboarding/onboard2.png
    - assets/images/onboarding/onboard3.png

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"
  background_image: assets/images/background.png

  image: assets/images/logo.png
  image_dark: assets/images/image_dark.png

  branding: assets/images/branding.png
  branding_dark: assets/images/branding_dark.png

  android_12:
    color: "#e4e4ed"
    image: assets/images/logo.png
    icon_background_color: "#e4e4ed"
    branding: assets/images/branding.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

