// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsOnFcY5JHQGBaTT4W1OiwQMtSjKpi42Y',
    appId: '1:599547580554:web:309a00241a577b65ad1d73',
    messagingSenderId: '599547580554',
    projectId: 'gradswap-90fa0',
    authDomain: 'gradswap-90fa0.firebaseapp.com',
    storageBucket: 'gradswap-90fa0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-W-Jf86MBTwa75DGZDxLZkvhv8zwWCf8',
    appId: '1:599547580554:android:1b696b0e8452bddcad1d73',
    messagingSenderId: '599547580554',
    projectId: 'gradswap-90fa0',
    storageBucket: 'gradswap-90fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAimugffZ8JlkjvMy7xZ74QEAbXshQGeDg',
    appId: '1:599547580554:ios:dec961773ebec0efad1d73',
    messagingSenderId: '599547580554',
    projectId: 'gradswap-90fa0',
    storageBucket: 'gradswap-90fa0.firebasestorage.app',
    iosBundleId: 'com.example.gradswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAimugffZ8JlkjvMy7xZ74QEAbXshQGeDg',
    appId: '1:599547580554:ios:dec961773ebec0efad1d73',
    messagingSenderId: '599547580554',
    projectId: 'gradswap-90fa0',
    storageBucket: 'gradswap-90fa0.firebasestorage.app',
    iosBundleId: 'com.example.gradswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsOnFcY5JHQGBaTT4W1OiwQMtSjKpi42Y',
    appId: '1:599547580554:web:95a94ee9ddedc5b0ad1d73',
    messagingSenderId: '599547580554',
    projectId: 'gradswap-90fa0',
    authDomain: 'gradswap-90fa0.firebaseapp.com',
    storageBucket: 'gradswap-90fa0.firebasestorage.app',
  );
}
